notEthan/jsi

lib/jsi/schema.rb

Schema#schema_jsi / @schema_jsi, not @schema_object. #schema_object will refer to jsi or node.

schema @schema_jsi

---

lib/jsi/base.rb
lib/jsi/schema.rb

remove Schema#describes_array? and Schema#describes_hash? - these methods are not too good and not too needed
easy enough to restore in the future if they seem of any value.

rm Schema#describes_array? and Schema#describes_hash?

---

README.md
lib/jsi/base.rb
test/base_test.rb
test/schema_instance_json_coder_test.rb
test/util_test.rb

while it may arguably be better for a JSI to treat hash keys that are symbols as if they were strings, calling deep_stringify_symbol_keys in Base#initialize is, for one thing, very much a half-assed solution since `some_jsi[:foo]` is not the same as `some_jsi['foo']`, and also problematic in that the JSI's instance then may or may not refer to the same actual object as the instance that was passed to #initialize.
in the future I _might_ decide that Base#initialize does a deep stringifying copy of its instance _if_ I fully implement something more like ActiveSupport::HashWithIndifferentAccess within JSI::Base. but I kind of doubt it.

don't stringify hash keys in Base#initialize

---

lib/jsi/json-schema-fragments.rb
lib/jsi/json/node.rb
lib/jsi/typelike_modules.rb
test/jsi_json_arraynode_test.rb
test/jsi_json_hashnode_test.rb
test/test_helper.rb

this is mainly duck-typing #to_hash / #to_ary on JSI::JSON::Node and helper methods. and of course many tests.

JSI::JSON::Node content may be any type

---

lib/jsi/base.rb

when subscripting, get the JSI class for a schema from an instance method
this lets a subclass override the call to JSI.class_for_schema in certain cases

Base#class_for_schema

---

lib/jsi/schema.rb

trying to match {"$ref": "#/foo/bar"} against a schema generally does not give the desired result.
I think. not 100% on this. openapi handles refs a little bit weirdly and this would match to a ref schema. but I don't want that with openapi either.

deref an instance before attempting to match_to_instance(instance)

---

lib/jsi/base.rb

Base.name will not set the SchemaClasses constant if it exists. sometimes Class#name seems to return nil even when the class has been assigned to a constant. weird.
this is only a thing I have noticed when using autocompletion in irb. it invokes #name, as you'd expect, but Class#name is returning nil.
I could check that the const_get for schema_classes_const_name is == self, but I think that's unnecessary.

bugfix JSI::Base.name

---

lib/jsi/json-schema-fragments.rb
lib/jsi/json/node.rb

assign return value to local var before return because 'next' in byebug seems to have troubles without it.

minor refactor

---

lib/jsi/base.rb
test/base_array_test.rb
test/base_hash_test.rb
test/base_test.rb

no reason for a JSI's #instance to just be a JSI::JSON::Node. undesirable in fact. this allows a plain hash/array, or any other type that responds to #to_hash / #to_ary

JSI instance may be any type

---

lib/jsi/json/node.rb
test/base_array_test.rb
test/base_test.rb
test/jsi_json_arraynode_test.rb
test/jsi_json_hashnode_test.rb
test/jsi_json_node_test.rb

simplify JSI::JSON::Node. unify naming to the names used by PathedNode. drop methods I don't wish to be API.

JSON::Node naming

---

lib/jsi/base.rb
lib/jsi/json/node.rb
test/jsi_json_node_test.rb

this was a hack for OpenAPI's Reference / JsonReference, but we don't need it now, and it was quite incorrect to apply universally

remove implicit deref from JSI::Base#[] and Node#[]

---

lib/jsi/base.rb
lib/jsi/schema.rb
test/base_test.rb

Base#fully_validate, Schema#fully_validate_instance, Schema#fully_validate_schema pass errors_as_objects option to json-schema
https://github.com/notEthan/jsi/pull/79

fully_validate option errors_as_objects

---

lib/schemas/json-schema.org/draft-04/schema.rb
lib/schemas/json-schema.org/draft-06/schema.rb
test/base_array_test.rb
test/base_hash_test.rb
test/base_test.rb
test/schema_test.rb

moving away from a class for a schema and toward a module for a schema.
the drafts (`JSI::JSONSchemaOrgDraft06` etc) will be modules instead of classes.
tests prefer to check instantiation of schema module to schema class.

JSI schema module over class

---

lib/jsi/metaschema_node.rb
lib/jsi/schema.rb
lib/jsi/schema_classes.rb
test/base_test.rb

move accessor methods to a separate module which becomes included in the primary JSI schema module
this lets overridden accessor methods call #super

JSI schema accessor module

---

lib/jsi.rb
lib/jsi/schema.rb
lib/schemas/json-schema.org/draft-04/schema.rb
lib/schemas/json-schema.org/draft-06/schema.rb
test/metaschema_node_test.rb

just use the schema modules and their .schema method

remove constants which refer to metaschema instances

---

lib/jsi/schema_classes.rb
test/schema_module_test.rb

enable subscript and accessor methods on Schema modules by extending SchemaModule modules with their metaschema's accessor module, and instantiating wrapper NotASchemaModule for non-schema nodes of the schema

schema module subscripts and accessors

---

lib/jsi.rb
lib/jsi/base.rb
lib/jsi/schema_classes.rb
test/base_array_test.rb
test/base_hash_test.rb
test/base_test.rb

rm JSI::BaseHash and BaseArray; all their functionality now lives in PathedHashNode and PathedArrayNode

rm JSI::BaseHash and BaseArray

---

lib/jsi/base.rb
lib/jsi/json/node.rb
lib/jsi/metaschema_node.rb
lib/jsi/pathed_node.rb
lib/jsi/schema.rb
lib/jsi/schema_classes.rb
lib/jsi/typelike_modules.rb
test/base_test.rb
test/jsi_json_arraynode_test.rb
test/jsi_json_hashnode_test.rb
test/jsi_json_node_test.rb
test/metaschema_node_test.rb

fix some names. prefix some things with `jsi_` to reduce collisions for accessors on Base. change some references to 'node' that weren't very meaningful.

names and prefixes

---

lib/jsi/base.rb
lib/jsi/metaschema_node.rb
lib/jsi/metaschema_node/bootstrap_schema.rb
lib/jsi/schema.rb
lib/jsi/schema/schema_ancestor_node.rb

incomplete; Schema#schema_absolute_uri  relies on not-yet-implemented #id_without_fragment

SchemaAncestorNode extends Base with #jsi_subschema_base_uri, #jsi_subschema_resource_ancestors, #schema_absolute_uri

---

lib/jsi/schema.rb
lib/jsi/schema/draft04.rb
lib/jsi/schema/draft06.rb
test/schema_test.rb

implementing these allows Schema#schema_absolute_uri to work properly
enables schema_absolute_uri to work (https://github.com/notEthan/jsi/pull/114)

Schema#id, #id_without_fragment

---

lib/jsi/base.rb
lib/jsi/metaschema_node.rb
lib/jsi/schema.rb

including DescribesSchema is removed in favor of setting the schema's jsi_schema_instance_modules
this no longer worked as of https://github.com/notEthan/jsi/pull/121

remove support for include DescribesSchema

---

lib/jsi/schema.rb

this only makes a difference when we will need to reinstantiate objects not described as schemas by a schema-describing-schema.

evaluating subschemas always results in a jsi

---

lib/jsi.rb
lib/jsi/schema.rb
lib/jsi/schema_classes.rb
lib/jsi/schema_set.rb
test/base_test.rb
test/schema_test.rb

no longer an expected entry point for instantiating schemas

deprecate JSI.class_for_schemas

---

lib/jsi/schema.rb
test/unsupported_test.rb

unsupported. undocumented. unwanted.

Schema.ensure_schema may reinstantiate nonschemas as schemas

---

lib/jsi/util.rb
test/base_mutation_test.rb

child instances' schemas would not be recalculated when the instance was mutated. comparing the memomap result inputs by equality, no change is detected as the mutation applies to the memo inputs the same as the instance - obviously, since they're the same object.
so, store the hash of the inputs as well as the inputs, and compare both. (comparing just the hash would have a possibility of collision.) this is a bit expensive and significantly impacts performance.
there's a minuscule chance that modified inputs have a hash collision (same hash before and after modification) and no change is detected. I'd rather have memomap result inputs store a frozen copy, but that's much more expensive still, and the chance of collision is probably negligible.

Base mutation

---

lib/jsi/schema/application/child_application/contains.rb
lib/jsi/schema/application/inplace_application/someof.rb
test/base_mutation_test.rb
test/schema_child_application_test.rb
test/schema_inplace_application_test.rb

schemas whose application depends on validation results should apply when the validation fails, so that checking the validity of children will not incorrectly return valid due to not having the failing schema applied to validate against

Invalid application

---

lib/jsi/base.rb
lib/jsi/base/node.rb
lib/jsi/metaschema_node.rb
test/base_array_test.rb
test/base_hash_test.rb
test/jsi_helper.rb
test/test_helper.rb

defaulting to insert schema default values is confusing if you're not expecting it. certain metaschemas having a default of `{}` or `true` in particular leads to masked bugs.

`Base#[]` param `use_default` default `false`, overridable
