notEthan/jsi

- lib/jsi/base.rb
- lib/jsi/base/to_rb.rb
- lib/jsi/schema.rb
- rename to Schema#described_object_property_names
- rm Schema#describes_array? and Schema#describes_hash?
> Schema described object

- lib/jsi/json/node.rb
- test/schema_test.rb
> Test schema

- lib/jsi/typelike_modules.rb
- lib/jsi/util.rb
improvements to #to_hash / #to_ary duck typing
> duck typing in util, typelike

- lib/jsi/json-schema-fragments.rb
- lib/jsi/json.rb
- lib/jsi/json/node.rb
- lib/jsi/json/pointer.rb
- lib/jsi/schema.rb
- test/jsi_json_node_test.rb
JSI::JSON::Pointer is the new home of ::JSON::Schema::Pointer
> JSI::JSON::Pointer

- test/jsi_json_pointer_test.rb
test JSI::JSON::Pointer initialize and evaluate from pointer and fragment
> test JSI::JSON::Pointer

- lib/jsi/typelike_modules.rb
- test/jsi_typelike_as_json_test.rb
handle JSI classes better; add tests.
> Typelike.as_json dev + test

- lib/jsi/base.rb
- lib/jsi/json-schema-fragments.rb
- lib/jsi/json/node.rb
- lib/jsi/json/pointer.rb
- lib/jsi/schema.rb
- lib/jsi/util.rb
- test/base_array_test.rb
- test/base_hash_test.rb
- test/base_test.rb
- test/jsi_json_arraynode_test.rb
- test/jsi_json_hashnode_test.rb
- test/jsi_json_node_test.rb
- test/jsi_json_pointer_test.rb
- test/util_test.rb
JSI::JSON::Node uses pointer instead of path
and some other stuff
> JSI::JSON::Node uses pointer instead of path

- lib/jsi/json/pointer.rb
> JSI::JSON::Pointer dev

- lib/jsi/base.rb
- lib/jsi/schema.rb
- test/base_array_test.rb
- test/base_hash_test.rb
- test/base_test.rb
- test/schema_test.rb
this is in preparation for JSI::Base handling its own document node pathing with JSI::PathedNode https://github.com/notEthan/jsi/pull/30
> JSI::Base instance is not a JSI::JSON::Node

- README.md
- lib/jsi/base.rb
- lib/jsi/json/node.rb
- lib/jsi/pathed_node.rb
- lib/jsi/schema.rb
- lib/jsi/typelike_modules.rb
- test/base_test.rb
- test/schema_test.rb
> JSI::Base node pathing

- lib/jsi/schema_classes.rb
JSI::SchemaModule, extending any JSI Schema Module
> JSI::SchemaModule

- lib/jsi/base.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/schema.rb
- lib/jsi/schema_classes.rb
- lib/jsi/util.rb
I hate the underscore variable names, I'm just going to shadow the variables. I never want the unshadowed variable.
> Shadow variables

- lib/jsi/schema.rb
> JSI::Schema#new_jsi will match_to_instance before instantiating

- lib/jsi/base.rb
- lib/jsi/json/node.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/schema.rb
- lib/jsi/schema_classes.rb
- lib/jsi/typelike_modules.rb
- lib/jsi/util.rb
- test/base_array_test.rb
- test/base_hash_test.rb
- test/base_test.rb
- test/jsi_typelike_as_json_test.rb
- test/schema_test.rb
- test/util_test.rb
remove the godawful generated schema id; indicate what's schema and metaschema; etc
> improve strings (inspect + to_s)

- lib/jsi/schema_classes.rb
- test/base_test.rb
not compatible with the future
> remove JSI::SchemaClasses[] classes_by_id

- lib/jsi/base.rb
- lib/jsi/json/node.rb
- lib/jsi/json/pointer.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/schema.rb
- lib/jsi/schema_classes.rb
- lib/jsi/util.rb
- test/base_array_test.rb
- test/base_hash_test.rb
- test/base_test.rb
- test/jsi_json_node_test.rb
- test/schema_test.rb
- test/test_helper.rb
move most common words included on JSI::Base to jsi_ preifx
> jsi_ prefix

- lib/jsi/base.rb
no longer have any need allow an ancestor that isn't simply the root.
> change Base ancestor_jsi to jsi_root_node

- README.md
- test/base_test.rb
things missed in     https://github.com/notEthan/jsi/pull/70
> jsi_ prefix fixes

- Gemfile
- lib/jsi.rb
- lib/jsi/base.rb
- lib/jsi/json/pointer.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/schema.rb
- lib/jsi/schema_classes.rb
- test/base_array_test.rb
- test/base_hash_test.rb
- test/base_test.rb
- test/metaschema_node_test.rb
- test/schema_test.rb
a JSI schema instance (JSI::Base, JSI::MetaschemaNode) has multiple schemas. instance.schema is now instance.jsi_schemas.
> schema instances may have multiple schemas

- lib/jsi/base.rb
multiline hashes / keyword argument lists. helps with readability and with merge conflicts.
> multiline key/value things

- Gemfile
- jsi.gemspec
update development dependencies to release versions - scorpio, ur, spreedly_openapi
> development dependency gem updates

- README.md
- lib/jsi.rb
- lib/jsi/schema.rb
- lib/jsi/schema_classes.rb
- lib/jsi/simple_wrap.rb
- test/base_array_test.rb
- test/base_hash_test.rb
- test/base_test.rb
- test/jsi_coder_test.rb
- test/jsi_typelike_as_json_test.rb
- test/schema_module_test.rb
- test/schema_test.rb
- test/util_test.rb
new_schema is a better name to instantiate a new schema
> JSI.new_schema, metaschema #new_schema

- test/metaschema_node_test.rb
metaschema node test refactor and expansion
> test improvements

- lib/jsi/base.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/metaschema_node/bootstrap_schema.rb
- lib/jsi/schema.rb
- lib/jsi/schema/schema_ancestor_node.rb
setters for jsi_document, jsi_ptr.
new_schema param base_uri
jsi_schema_base_uri on MetaschemaNode and MetaschemaNode::BootstrapSchema
some of this should have been in https://github.com/notEthan/jsi/pull/114
> SchemaAncestorNode dev

- lib/jsi/util.rb
helper module for a virtual base class
> JSI::Util::Virtual

- lib/jsi/base.rb
- lib/jsi/json/pointer.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/pathed_node.rb
- lib/jsi/schema.rb
- lib/jsi/schema/application/inplace_application.rb
- lib/jsi/schema/ref.rb
- lib/jsi/util.rb
replace Pointer#deref, Base#deref, MetaschemaNode#deref, PathedNode#jsi_ptr_deref with Schema::Ref
> Schema::Ref

- lib/jsi/schema/ref.rb
https://github.com/notEthan/jsi/pull/156 + https://github.com/notEthan/jsi/pull/162
> Schema::Ref anchor find + jsi_each_child_node

- lib/jsi/schema/application/inplace_application.rb
- visited_refs prevent infinite recursion
- $ref ignores siblings (on currently supported drafts)
> Schema#match_to_instance dev

- lib/jsi/schema_classes.rb
- test/base_test.rb
refactor & avoid defining bad ones
> schema module accessors

- lib/jsi.rb
- lib/jsi/schema.rb
- lib/jsi/schema_registry.rb
- lib/schemas/json-schema.org/draft-04/schema.rb
- lib/schemas/json-schema.org/draft-06/schema.rb
eliminates need for Schema.supported_metaschemas
> SchemaRegistry autoload_uri

- lib/jsi/base.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/schema/application.rb
- lib/jsi/schema/application/child_application.rb
- lib/jsi/schema/application/child_application/contains.rb
- lib/jsi/schema/application/child_application/draft04.rb
- lib/jsi/schema/application/child_application/draft06.rb
- lib/jsi/schema/application/child_application/items.rb
- lib/jsi/schema/application/child_application/properties.rb
- lib/jsi/schema/application/draft04.rb
- lib/jsi/schema/application/draft06.rb
- lib/jsi/schema/application/inplace_application.rb
- lib/jsi/schema/application/inplace_application/dependencies.rb
- lib/jsi/schema/application/inplace_application/draft04.rb
- lib/jsi/schema/application/inplace_application/draft06.rb
- lib/jsi/schema/application/inplace_application/ref.rb
- lib/jsi/schema/application/inplace_application/someof.rb
- lib/jsi/schema/draft04.rb
- lib/jsi/schema/draft06.rb
- lib/jsi/schema_set.rb
- test/metaschema_node_test.rb
- test/schema_child_application_test.rb
- test/schema_inplace_application_test.rb
- test/schema_test.rb
rekafoobling the applicatomotron
> Schema Application

- lib/jsi/util.rb
- lib/jsi/util/private.rb
- lib/jsi/util/private/attr_struct.rb
separate JSI::Util into public utilities (subject to semver) and private
> Util::Private

- lib/jsi/base.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/pathed_node.rb
- lib/jsi/ptr.rb
- lib/jsi/schema.rb
- lib/jsi/schema/schema_ancestor_node.rb
- lib/jsi/schema_classes.rb
- lib/jsi/typelike_modules.rb
- lib/jsi/util/private.rb
- test/base_array_test.rb
- test/base_hash_test.rb
- test/json_schema_suite_test.rb
get keyword arguments compatible with ruby 3
> splat keywords

- lib/jsi/schema.rb
JSI::Schema.default_metaschema has no default
> remove default metaschema

- lib/jsi/base.rb
- lib/jsi/metaschema_node.rb
- lib/jsi/ptr.rb
- lib/jsi/schema.rb
- lib/jsi/schema/ref.rb
- lib/jsi/schema/schema_ancestor_node.rb
- lib/jsi/schema_registry.rb
- test/base_test.rb
- test/json_schema_suite_test.rb
- test/metaschema_node_test.rb
- test/schema_test.rb
- test/unsupported_test.rb
fix usage of 'child' where I mean 'descendent'
> JSI descendent nodes

- lib/jsi/base/node.rb
- lib/jsi/schema_classes.rb
- test/base_test.rb
enables `node.jsi_each_descendent_node.grep(/regexp/)`
> Base::StringNode

- lib/jsi/base.rb
- lib/jsi/metaschema_node/bootstrap_schema.rb
- lib/jsi/schema/schema_ancestor_node.rb
- lib/jsi/schema_set.rb
simplify; drop debug checks and unnecessary setters
> ivar assignment

- lib/jsi/metaschema_node.rb
- test/metaschema_node_test.rb
and test that a metaschema can validate itself
> MetaschemaNode#jsi_indicated_schemas

- lib/jsi/schema_classes.rb
instead of module SchemaModule extending each schema module
> class SchemaModule < Module
